name: Evaluate PR

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-evaluation:
    runs-on: ubuntu-latest
    # Only run if PR author has write access
    if: |
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'

    steps:
      - name: Trigger interactionTasks_v6 Evaluation
        id: trigger
        continue-on-error: true
        run: |
          echo "🚀 Triggering evaluation for PR #${{ github.event.pull_request.number }}"
          echo "Commit: ${{ github.event.pull_request.head.sha }}"

          response=$(curl -X POST \
            "${{ secrets.EVAL_PLATFORM_URL }}/api/triggerInteractionTasksV6" \
            -H "Authorization: Bearer ${{ secrets.EVAL_PLATFORM_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"commitSha\": \"${{ github.event.pull_request.head.sha }}\",
              \"prNumber\": ${{ github.event.pull_request.number }},
              \"githubRepo\": \"${{ github.repository }}\"
            }" -s)

          echo "Response: $response"

          # Check if trigger was successful
          if echo "$response" | jq -e '.success == true' > /dev/null; then
            echo "✅ Evaluation triggered successfully"
            echo "📊 Results will be posted automatically when evaluation completes (~25 minutes)"
            exit 0
          else
            echo "❌ Failed to trigger evaluation"
            echo "$response"
            exit 1
          fi

      - name: Post initial comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const triggerSuccess = '${{ steps.trigger.outcome }}' === 'success';
            const commitSha = '${{ github.event.pull_request.head.sha }}';
            const workflowUrl = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';

            let body;
            if (triggerSuccess) {
              body = `🚀 **Evaluation triggered** for commit \`${commitSha}\` `;
            } else {
              body = `**Evaluation failed** for commit \`${commitSha}\`. Check [workflow logs](${workflowUrl}).`;
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
